# Generated by Django 2.0.4 on 2018-05-06 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CommentBase',
            fields=[
                ('comment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='comment.Comment')),
                ('text', models.CharField(max_length=500)),
            ],
            bases=('comment.comment',),
        ),
        migrations.CreateModel(
            name='CommentDecorator',
            fields=[
                ('comment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='comment.Comment')),
            ],
            bases=('comment.comment',),
        ),
        migrations.CreateModel(
            name='CommentImage',
            fields=[
                ('commentdecorator_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='comment.CommentDecorator')),
                ('image', models.CharField(max_length=30)),
            ],
            bases=('comment.commentdecorator',),
        ),
        migrations.AddField(
            model_name='commentdecorator',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decorator', to='comment.Comment'),
        ),
    ]
