# Generated by Django 2.0.4 on 2018-05-06 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20180506_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentdecorator',
            name='comment_ptr',
        ),
        migrations.AlterField(
            model_name='commentdecorator',
            name='comment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='comment.Comment'),
        ),
    ]
